<a href="https://colab.research.google.com/github/PavliukAlina7041/Lab04/blob/main/%22Lab04__ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3.1. Series

3.1.8. Створіть Series зі списку рядків. Визначте довжину
кожного рядка та знайдіть найдовший.

In [ ]:
import pandas as pd

data = ["Київ", "Львів", "Вінниця", "Полтава", "Дніпро"]
series = pd.Series(data)

lengths = series.str.len()

longest_string = series[lengths == lengths.max()]

print("Початковий Series:")
print(series, "\n")

print("Довжина кожного рядка:")
print(lengths, "\n")

print(f"Найдовший рядок: \n {longest_string} ")

Початковий Series:
0       Київ
1      Львів
2    Вінниця
3    Полтава
4     Дніпро
dtype: object

Довжина кожного рядка:
0    4
1    5
2    7
3    7
4    6
dtype: int64

Найдовший рядок:
 2    Вінниця
3    Полтава
dtype: object

# 3.2. DataFrame

3.2.8. Дано словник:

employees = {
"name": ["Ivan", "Maria", "Petro",
"Olha"], "department": ["IT", "HR", "IT",
"HR"],
"salary": [20000, 18000, 22000, 19000]
}


Створіть DataFrame.
Збільште зарплату кожного співробітника на 10%.
Відсортуйте таблицю за department, а всередині відділу - за
salary.

In [4]:
import pandas as pd

employees = {
    "name": ["Ivan", "Maria", "Petro", "Olha"],
    "department": ["IT", "HR", "IT", "HR"],
    "salary": [20000, 18000, 22000, 19000]
}

empl = pd.DataFrame(employees)
empl['salary'] = empl['salary'] * 1.1

empl_sorted = empl.sort_values(by=['department', 'salary'], ascending=[True, False])

empl_sorted

    name department   salary
3   Olha         HR  20900.0
1  Maria         HR  19800.0
2  Petro         IT  24200.0
0   Ivan         IT  22000.0

# 3.3. Робота з файлами в Pandas (CSV, Excel)

3.3.8. Файл products.csv:



---


product,price,quantity


Laptop,25000,5


Mouse,500,0


Keyboard,1200,10


Monitor,7000,3



---


Зчитайте дані у DataFrame.
Видаліть рядки, де quantity дорівнює 0.
Збережіть результат у products_available.csv.

In [5]:
import os
from google.colab import userdata


TOKEN = userdata.get('GITHUB_TOKEN')


USERNAME = "PavliukAlina7041"
REPO_NAME = "Lab04"


repo_url = f"https://{USERNAME}:{TOKEN}@github.com/{USERNAME}/{REPO_NAME}.git"


!git clone {repo_url}


os.chdir(REPO_NAME)

Cloning into 'Lab04'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 12 (delta 2), reused 5 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (12/12), done.
Resolving deltas: 100% (2/2), done.

In [ ]:
import pandas as pd
df = pd.read_csv("products.csv")
df_available = df[df["quantity"] != 0]
df_available.to_csv("products_available.csv", index=False)

!git config --global user.email "pavliukalina@knu.ua"
!git config --global user.name "Alina Pavliuk"


!git add products_available.csv
!git commit -m "Додано products_available.csv"
!git push origin main

print('Done')

[main 23d159b] Додано products_available.csv
 1 file changed, 4 insertions(+), 5 deletions(-)
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 351 bytes | 351.00 KiB/s, done.
Total 3 (delta 1), reused 1 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/PavliukAlina7041/Lab04.git
   a0daba1..23d159b  main -> main
Done

# 3.5. Операція з Таблицями

**Вихідна таблиця 1 — students.csv**


student_id,name,group,year,faculty,city


1,Anna,A1,1,Physics,Kyiv


2,Bohdan,A1,2,Physics,Lviv


3,Iryna,B2,1,Math,Kyiv


4,Oleh,B2,3,Math,Odesa


5,Maria,C1,2,IT,Kharkiv


6,Dmytro,C1,4,IT,Kyiv


7,Olena,A2,1,Physics,Lviv


8,Andrii,A2,2,Physics,Kyiv


9,Natalia,B3,3,Math,Dnipro



10,Yurii,C2,1,IT,Odesa


11,Svitlana,C2,2,IT,Kyiv


12,Petro,B3,4,Math,Lviv


**Вихідна таблиця 2 — scores.csv**


student_id,subject,semester,score,teacher


1,Math,1,90,Petrenko


1,Physics,1,88,Ivanenko


2,Math,2,72,Petrenko


2,Physics,2,75,Ivanenko


3,Math,1,85,Petrenko


3,Physics,1,92,Ivanenko


4,Physics,3,65,Ivanenko


5,Math,2,78,Shevchenko


5,Informatics,2,82,Koval


6,Informatics,4,91,Koval


7,Physics,1,87,Ivanenko


8,Math,2,69,Petrenko


9,Math,3,74,Petrenko


9,Physics,3,70,Ivanenko


10,Informatics,1,88,Koval


11,Informatics,2,93,Koval


13,Math,1,80,Petrenko


14,Physics,2,76,Ivanenko


**3.5.8. Об’єднайте таблиці students і scores.**
Виберіть студентів, які склали всі предмети (score ≥ 60).
Порахуйте їх середній бал.

In [ ]:
import pandas as pd

st = pd.read_csv("students.csv")
sc = pd.read_csv("scores.csv")

result = pd.merge(st, sc, on='student_id', how='inner')

failed_students = result[result['score'] < 60]['student_id'].unique()

# (~ міняє умову на протилежну — "не входить до списку тих, хто не склав")
successful_students_df = result[~result['student_id'].isin(failed_students)]
average = successful_students_df['score'].mean()

print(f'Середній бал студентів, які склали всі предмети: {average:.2f}')
successful_students_df

Середній бал студентів, які склали всі предмети: 81.19

,student_id,name,group,year,faculty,city,subject,semester,score,teacher
0,1,Anna,A1,1,Physics,Kyiv,Math,1,90,Petrenko
1,1,Anna,A1,1,Physics,Kyiv,Physics,1,88,Ivanenko
2,2,Bohdan,A1,2,Physics,Lviv,Math,2,72,Petrenko
3,2,Bohdan,A1,2,Physics,Lviv,Physics,2,75,Ivanenko
4,3,Iryna,B2,1,Math,Kyiv,Math,1,85,Petrenko
5,3,Iryna,B2,1,Math,Kyiv,Physics,1,92,Ivanenko
6,4,Oleh,B2,3,Math,Odesa,Physics,3,65,Ivanenko
7,5,Maria,C1,2,IT,Kharkiv,Math,2,78,Shevchenko
8,5,Maria,C1,2,IT,Kharkiv,Informatics,2,82,Koval
9,6,Dmytro,C1,4,IT,Kyiv,Informatics,4,91,Koval
10,7,Olena,A2,1,Physics,Lviv,Physics,1,87,Ivanenko
11,8,Andrii,A2,2,Physics,Kyiv,Math,2,69,Petrenko
12,9,Natalia,B3,3,Math,Dnipr,Math,3,74,Petrenko
13,9,Natalia,B3,3,Math,Dnipr,Physics,3,70,Ivanenko
14,10,Yurii,C2,1,IT,Odesa,Informatics,1,88,Koval
15,11,Svitlana,C2,2,IT,Kyiv,Informatics,2,93,Koval